version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: adres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d adres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend  # Connect to the network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: dockerpinguin/adres:latest  # Change to match your built image version
    networks:
      - backend  # Connect to the network
    container_name: my_spring_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/adres
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: runtime
    command: ["java", "-Dspring.profiles.active=runtime", "-jar", "/app.jar"]
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  backend:  # Give your network a descriptive name
    driver: bridge

volumes:
  postgres_data:

