info:
  environment: runtime

logging:
  level:
    org:
      springframework: info
    com:
      bsoft: debug

management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    shutdown:
      enabled: true
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: '*'
        exclude:

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./adres
    username: sa
    password: sa
  flyway:
    enabled: true
    url: jdbc:h2:./adres
    user: sa
    password: sa
    validateMigrationNaming: true
    locations: classpath:db/migration/h2
  h2:
    console.enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  security:
    user:
      name: testuser
      password: 12345
      roles: admin, user

springdoc:
  enable-spring-security: false
  show-actuator: true
