application:
  key: "9dd059be604f3e0b8742724eae817a49d4561fe22bf3519d10d7431dd4b188e4" # using jwtsecret.com/generate 32 bytes 256 bits
  key-lifetime: 1000000 # ms
  basePath: "/adres/api/v1"

logging:
  level:
    org:
      apache:
        http: info
      springframework:
        security: info
    com:
      bsoft: debug

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  mvc:
    problem-details:
      enabled: true
  profiles:
    active: '@activeProfile@'

springdoc:
  enable-spring-security: false
  show-actuator: true
  swagger-ui:
    show-common-extensions: true
    with-credentials: false
#    url: http://localhost:8080/swagger-ui/index.html
    path: /swagger-ui/index.html
    tagsSorter: alpha
    validator-url: "https://validator.swagger.io/validator"

info:
  project:
    name: ${spring.application.name}
    version: @project.version@
    description: @project.description@
  environment: ${spring.profiles.active}
