logging:
  level:
    org:
      springframework:
        security: info
        spring-doc: trace
    com:
      bsoft: debug

management:
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: 'health,info,prometheus'
        exclude:
  info:
    build:
      enabled: false
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/adres
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/adres
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration/postgresql
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        fomat_sql: true

