info:
  app:
    name: "@{project.name}@"  # Reference using SpEL
    description: "@{project.description}@"
    version: "@{project.version}@"
    encoding: "@{project.build.sourceEncoding}@"
    java:
      source: "@{java.version}@"
      target: "@{java.version}@"

logging:
  level:
    org:
      apache:
        http: info
      springframework: info
    com:
      bsoft: info

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    info:
      env:
        enabled: true
      git:
        mode: full
        enabled: true
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: '*'
        exclude:
  server:
    port: 8081

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/adres
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/adres
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  mvc:
    problemdetails:
      enabled: true

springdoc:
  enable-spring-security: true
  show-actuator: true
  swagger-ui:
    show-common-extensions: true
    with-credentials: false
    url: http://localhost:8080/swagger-ui/index.html
