info:
  project:
    name: @project.name@
    version: @project.version@
    description: @project.description@

logging:
  level:
    org:
      apache:
        http: info
      springframework:
        security: info
    com:
      bsoft: debug

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    build:
      enabled: false
    env:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: 'health,info'
        exclude:
  server:
    port: 8081

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  mvc:
    problemdetails:
      enabled: true

springdoc:
  enable-spring-security: false
  show-actuator: true
  swagger-ui:
    show-common-extensions: true
    with-credentials: false
    url: http://localhost:8080/swagger-ui/index.html
