info:
  environment: runtime


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/adres
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/adres
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration/postgresql
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
