info:
  project:
    name: @project.name@
    version: @project.version@
    description: @project.description@

logging:
  level:
    org:
      apache:
        http: info
      springframework:
        security: debug
    com:
      bsoft: debug

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  mvc:
    problemdetails:
      enabled: true


