info:
  project:
    name: @project.name@
    version: @project.version@
    description: @project.description@

logging:
  level:
    org:
      apache:
        http: info
      springframework: info
    com:
      bsoft: info

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    build:
      enabled: false
    env:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: 'health,info'
        exclude:
  server:
    port: 8081

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/adres
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/adres
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration/postgresql
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  mvc:
    problemdetails:
      enabled: true

springdoc:
  enable-spring-security: true
  show-actuator: true
  swagger-ui:
    show-common-extensions: true
    with-credentials: false
    url: http://localhost:8080/swagger-ui/index.html
