logging:
  level:
    org:
      springframework: info
      springdoc: debug
      web: trace
    com:
      bsoft: debug

management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only
    shutdown:
      access: unrestricted
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: '*'
        exclude:
  server:
    port: 8081


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./adres
    username: sa
    password: sa
  flyway:
    enabled: true
    url: jdbc:h2:file:./adres
    user: sa
    password: sa
    validateMigrationNaming: true
    locations: classpath:db/migration/h2
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        fomat_sql: true
