info:
  project:
    name: @project.name@
    version: @project.version@
    description: @project.description@
  environment: '@activeProfile@'

logging:
  level:
    org:
      apache:
        http: info
      springframework:
        security: info
    com:
      bsoft: debug

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  mvc:
    problemdetails:
      enabled: true

#spring-boot:
#  run:
#    profiles: '@activeProfile'
#  test:
#    profiles: '@activeProfile'
#  active:
#    profile: '@activeProfile'


springdoc:
  enable-spring-security: false
  show-actuator: true
  swagger-ui:
    show-common-extensions: true
    with-credentials: false
    url: http://localhost:8080/swagger-ui/index.html
    tagsSorter: alpha
