###
GET http://localhost:8081/actuator
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Basic YWRtaW46MTIzNDU=

###
POST http://localhost:8080/adres/api/v1/adresses
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "street": "Kerkewijk",
  "housenumber": "125",
  "zipcode": "3904 JB",
  "city": "Veenendaal"
}

> {%
    console.log('response status: ' + response.status)
    console.log(response)
    console.log('"body": ' + JSON.stringify(response.body, null, " "))
%}

###
POST http://localhost:8080/adres/api/v1/adresses?override=true
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "street": "Kerkewijk",
  "housenumber": "123",
  "zipcode": "3904 JB",
  "city": "Veenendaal"
}

> {%
    console.log('response status: ' + response.status)
    console.log(response)
    console.log('"body": ' + JSON.stringify(response.body, null, " "))
%}


###
GET http://localhost:8080/adres/api/v1/adresses?size=5&sort=-id,-street
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
GET http://localhost:8080/adres/api/v1/adresses?size=5&page=4
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077


###
GET http://localhost:8080/adres/api/v1/adresses?page=1
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
GET http://localhost:8080/adres/api/v1/adresses?page=1&size=2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077


###
GET http://localhost:8080/adres/api/v1/adresses?page=2&size=2
Accept: application/json
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
GET http://localhost:8080/adres/api/v1/adresses?sort=zipcode,id
Accept: application/json
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
GET http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077


###
PATCH http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "street": "Molenplein",
  "housenumber": "5",
  "zipcode": "4021 XY",
  "city": "Waalwijk"
}

###
PATCH http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "street": "Kerkewijk"
}

###
PATCH http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "housenumber": "124"
}

###
PATCH http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "zipcode": "3904 JB"
}

###
PATCH http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "city": "Veenendaal"
}

###
PATCH http://localhost:8080/adres/api/v1/adresses/2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Basic bvpelt 12345

{
  "street": "Kerkewijk",
  "housenumber": "124",
  "zipcode": "3904 JB",
  "city": "Veenendaal",
  "adresId": 3
}

###
GET http://localhost:8080/adres/api/v1/adresses
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
DELETE http://localhost:8080/adres/api/v1/adresses/4
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
GET http://localhost:8080/adres/api/v1/persons?size=2
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
GET http://localhost:8080/adres/api/v1/users/1
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

###
POST http://localhost:8080/adres/api/v1/login/jwt/authenticate
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

{
  "username": "bvpelt",
  "password": "12345"
}
> {%
    client.global.set("auth_token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
%}

###
GET http://localhost:8080/adres/api/v1/users
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8080/adres/api/v1/login/user
Accept: application/json
Content-Type: application/json
x-api-key: f0583805-03f6-4c7f-8e40-f83f55b7c077

{
  "username": "user",
  "password": "12345"
}
