apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:                  # Specification deployment
  replicas: 2          # Changed from 1 -> 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:              # Specification pod
      containers:
        - name: nginx
          image: nginx:1.27.4
          ports:
          - containerPort: 8080
