apiVersion: apps/v1
kind: Deployment
metadata:
  name: adres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adres-app
  template:
    metadata:
      labels:
        app: adres-app
    spec:
      containers:
        - name: adres-app
          image: dockerpinguin/adres:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres/adres
            - name: SPRING_DATASOURCE_USERNAME
              value: testuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_PROFILES_ACTIVE
              value: runtime
          livenessProbe:
            httpGet:
              path: /actuator/app-health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          command: ["java", "-Dspring.profiles.active=runtime", "-jar", "/app.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: adres-app
spec:
  selector:
    app: adres-app
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: adres-app-external
spec:
  type: NodePort
  selector:
    app: adres-app
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-8081
      protocol: TCP
      port: 8081
      targetPort: 8081