apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: dockerpinguin/angular-app:latest
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: http://adres-app:8080/adres/api/v1
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80