apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: default
type: Opaque
data:
  admin-user: YWRtaW4=   # "admin" (base64 encoded)
  admin-password: cGFzc3dvcmQ=  # "password" (base64 encoded) using https://www.base64encode.org/
