apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: default
data:
#  datasources.yaml: |
  prometheus.yaml: |-    
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: "5s"
        editable: true
