apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      initContainers:
        - name: wait-for-configmap
          image: busybox
          command: ['sh', '-c', 'until [ -f /etc/prometheus/prometheus.yml ]; do echo "Waiting for config map..."; sleep 2; done;']
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          startupProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 15  # Wait before first probe
            periodSeconds: 5         # Check every 5 sec
            timeoutSeconds: 3        # Fail if no response in 3 sec
            failureThreshold: 10     # Fail after 10 failed attempts (50 sec total)
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            optional: false
