apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "adres-app"
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["adres-app:8081"]

#      - job_name: "node-exporter"
#        static_configs:
#          - targets: ["node-exporter:9100"]
