create table roles_privileges
(
    id     bigint not null primary key,
    privilegeid bigint,
    roleid bigint
);

ALTER TABLE roles_privileges
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME roles_privileges_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);
create index roles_privileges_userid_ix on roles_privileges (privilegeid);
create index roles_privileges_roleid_ix on roles_privileges (roleid);

