create table person
(
    personid  bigint not null primary key,
    firstname text   not null,
    infix     text,
    lastname  text   not null,
    hash      int
);

ALTER TABLE person
ALTER
COLUMN personid ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME personid_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);