create table users
(
    userid   bigint       not null primary key,
    username varchar(24)  not null,
    password varchar(48)  not null,
    email    varchar(128) not null,
    phone    varchar(24)
);

ALTER TABLE users
ALTER
COLUMN userid ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME users_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);

create index users_username_ix on users (username);
create index users_email_ix on users (email);

