create table adres_person
(
    id  bigint not null primary key,
    adresid  bigint not null,
    personid  bigint not null
);


create index ap_adres_ix on adres_person(adresid);
create index ap_person_ix on adres_person(personid);

ALTER TABLE adres_person
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME adres_person_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
)