create table role
(
    id          bigint      not null primary key,
    rolename    varchar(32) not null,
    description varchar(128),
    hash        int
);

create unique index role_rolename_ix on role (rolename);

ALTER TABLE role
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME role_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);


