create table users_roles
(
    id     bigint not null primary key,
    userid bigint,
    roleid bigint
);

ALTER TABLE users_roles
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME users_roles_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);

create index users_roles_userid_ix on users_roles (userid);
create index users_roles_roleid_ix on users_roles (roleid);

