create table apikey
(
    id          bigint not null primary key,
    apikey      text   not null,
    inuse       boolean
);

create unique index apikey_ix on apikey (apikey, inuse);

ALTER TABLE apikey
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME apikey_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);
