create table adres
(
    adresid bigint not null primary key,
    street text not null,
    housenumber text not null,
    zipcode text,
    city text not null,
    hash int
);

ALTER TABLE adres
    OWNER TO testuser;

ALTER TABLE adres
ALTER
COLUMN adresid ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME adresid_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);
