{
 "title": "Adres application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Adressen",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Adres\", uri=~\"/adres/api/v1/adresses.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Persons",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Adres\", uri=~\"/adres/api/v1/persons.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "User",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Adres\", uri=~\"/adres/api/v1/users.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Adres\", uri=~\"/adres/api/v1/roles.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Privilege",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Adres\", uri=~\"/adres/api/v1/privileges.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Login / Logout",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"Adres\", uri=~\"/adres/api/v1/log.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  }
 ]
}