apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version}}"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres/adres
            - name: SPRING_DATASOURCE_USERNAME
              value: testuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_PROFILES_ACTIVE
              value: runtime
            - name: activeProfile
              value: runtime
          livenessProbe:
            httpGet:
              path: /actuator/app-health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:   # ✅ Add this to delay service traffic until app is ready
            httpGet:
              path: /actuator/app-health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for database; sleep 2; done;']
