apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseApp }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.databaseApp }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.databaseApp }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
